import  { Metadata } from 'next';
import style from './modalStyle.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function Layout(props) {
  return (
    <>
      {props.modal}
      {props.children}
    </>
  );
}